security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: 701f7ec3-9123-4965-b317-46a0d88832c0
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server


spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.96.104:3306/icmes_base_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: admin
    password: Taylor@2009
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    
mybatis:
  mapper-locations: classpath:com/dtelec/icmes/account/repository/dao/*.xml

icmes:
  version: 1.0
  debugWorkMode: true
  initPassword: 123456
  loginRetryCount: 5

server:
  servlet:
    context-path: /account
  port: 6000
