logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-center:8761/eureka/


security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5500/uaa/users/current
