spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.96.104:3306/icmes_base_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: admin
    password: Taylor@2009
   # url: jdbc:mysql://127.0.0.1:3306/my_icmes_base_dev?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
   # username: localmes
   # password: Local2018  
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

security:
  oauth2:
    client:
      clientId: information-service
      clientSecret: 701f7ec3-9123-4965-b317-46a0d88832c0
      accessTokenUri: http://auth-service:5500/uaa/oauth/token
      grant-type: client_credentials
      scope: server

    
mybatis:
  mapper-locations: classpath:com/dtelec/icmes/information/repository/dao/*.xml

icmes:
  version: 1.0
  commandTimeout: 5
  commandWorkerCount: 20
  debugWorkMode: true

server:
  servlet:
    context-path: /info
  port: 7000
